[package]
name = "desktop"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "keyway"
path = "src/main.rs"

[dependencies]

#
# Workspace member crates
#

assets.workspace = true
command.workspace = true
command-palette.workspace = true
workspace.workspace = true

#
# External crates
#

anyhow.workspace = true
gpui-kit.workspace = true
